name: KP Law Firm (Grid-manual)
favicon: null
layout_spectrum: 0.5343802259303629
typography_spectrum: 0.8977918054442853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.14514256035909057
  lightness: 0.15007566008716822
  saturation: 0.8054797926452011
  rhythmicContrast: 0.5878162723965943
purpose: []
